### ISSUE TITLE
请问可以分享一些相关的生成结果的视频吗？

### ISSUE THREAD

**Issue by DWCTOD** [wuhaozhe/style_avatar#1]
您好，感谢大佬开源的代码！
不知道是否可以分享一些生成结果的视频？谢谢啦

**Comment by wuhaozhe** [comment]
Hi, you can watch demo video with this link: https://hcsi.cs.tsinghua.edu.cn/demo/MM21-HAOZHEWU.mp4

**Comment by DWCTOD** [comment]
谢谢大佬

**Comment by miaoYuanyuan** [comment]
@wuhaozhe the link is 504 Gateway Time-out, another question: can I  test it  in chinese language?

**Comment by wuhaozhe** [comment]
> @wuhaozhe the link is 504 Gateway Time-out, another question: can I test it in chinese language?

Hey, we have fixed the website. The deepspeech is trained on English, you can test it in Chinese, but the result wouldn't be satisfactory.

**Comment by miaoYuanyuan** [comment]
Thank you ! I will test it.
