### ISSUE TITLE
运行demo.py，生成了很奇怪的结果

### ISSUE THREAD

**Issue by ruanjiyang** [wuhaozhe/style_avatar#11]
您好，非常感谢这么有意思的一个项目。 我完全按照你的步骤执行下来，直接运行demo.py

[然后生成了很奇怪的结果。请看下面的图片。

**Comment by ruanjiyang** [comment]
![截图](https://user-images.githubusercontent.com/45660925/154880232-17956679-078f-44fb-9a2e-004c34876989.jpg)

**Comment by wuhaozhe** [comment]
这些都是合成的中间结果啊

**Comment by ruanjiyang** [comment]
这么快的答复啊，第一次见。 很感谢。

问题是， 程序跑到这，就结束了啊。不知道哪里出错了。 请看截图。


![截图-2](https://user-images.githubusercontent.com/45660925/154880682-fda71cc5-92e7-4932-b983-4563025732c9.jpg)
。

**Comment by wuhaozhe** [comment]
checkpoint load失败了，pre-trained [reconstruction network](https://drive.google.com/file/d/176LCdUDxAj7T2awQ5knPMPawq5Q2RUWM/view)这个下载了吗？

**Comment by ruanjiyang** [comment]
我是下载了FaceReconModel.zip， 然后把里面的FaceReconModel.pb 取出来，放在目录 ./deep_3drecon/network中。 zip文件里面的其他三个文件我没有取出来。

**Comment by wuhaozhe** [comment]
重建用的这个框架: https://github.com/microsoft/Deep3DFaceReconstruction，你可以先配一下这个环境看能不能跑起来？可以的话里面一些和重建相关的文件迁移到我这个项目里？

**Comment by ruanjiyang** [comment]
我知道原因了， 是需要把deepspeech-0.9.2-checkpoint.tar.zip 先解压缩成tar，然后还需要把tar解压缩成目录，才可以。

**Comment by wuhaozhe** [comment]
好的~

**Comment by xiao-keeplearning** [comment]
@ruanjiyang 你好，问下你的tensorflow版本是多少的？我用的1.14版本 cuda只能用10.0才能正常用gpu
