### ISSUE TITLE
The code implementation is inconsistent with the paper

### ISSUE THREAD

**Issue by xiao-keeplearning** [wuhaozhe/style_avatar#12]
Thank you share awesome work!
In the code, you extract the speech features and **energy features** from the audio clips. However, in your paper, you only mentioned leveraging the DeepSpeech model to extract speech features.
Could you give me some advice for the above situation？

**Comment by wuhaozhe** [comment]
hey, that's because we find that deepspeech feature is very sparse, and do not reflect the Amplitude of motion, therefore we  add energy feature

**Comment by xiao-keeplearning** [comment]
Thanks for your reply!
