### ISSUE TITLE
 render 部分的noisy dots 有什么解决思路吗

### ISSUE THREAD

**Issue by kunyao2015** [wuhaozhe/style_avatar#15]
看到您提到的将要解决的问题，包含render 部分的noisy dots ， 我也有这种情况，有什么思路可以尝试吗？

**Comment by wuhaozhe** [comment]
这一部分是由于UV坐标存储在视频中，然后视频的有损编解码导致了。我在一个新的项目中已经解决了，不过还没有开源

**Comment by kunyao2015** [comment]
感谢作者回复，我再研究研究
