### ISSUE TITLE
demo.py生成的10种风格没有head pose

### ISSUE THREAD

**Issue by LangR7** [wuhaozhe/style_avatar#17]
你好，我运行python demo.py生成了10个result，发现他们均缺少pose部分，请问这是正常的吗？
![image](https://user-images.githubusercontent.com/54303737/168733051-15dca33e-e0d8-4ea5-a376-5a490e84f022.png)

**Comment by wuhaozhe** [comment]
是的，目前并没有公开预测多风格pose的模型(预测pose的效果不是很好)

**Comment by LangR7** [comment]
> 是的，目前并没有公开预测多风格pose的模型(预测pose的效果不是很好)

了解了，感谢回复
