### ISSUE TITLE
- Run `git lfs checkout ./deep_3drecon/BFM/BFM_model_front.mat`

### ISSUE THREAD

**Issue by anthonyyuan** [wuhaozhe/style_avatar#2]
hi:
   It do not work,can u give me some ad?

**Comment by wuhaozhe** [comment]
hi, BFM_model_front.mat is a binary file larger than 100 MB, therefore we cannot directly upload it to Github with `git push`, therefore we leverage Git Large File Storage (LFS) to replace large files with text pointers inside Git. The checkout command would replace text pointers to large files. 

You can install git lfs with command:
apt install git-lfs
git lfs install.

Optionally, there is a much easier solution, you can directly download BFM_model_front.mat and put it into the corresponding folder.
