### ISSUE TITLE
tex_encode.pkl load failed

### ISSUE THREAD

**Issue by liyuanyaun** [wuhaozhe/style_avatar#5]
hi, i have loaded 'backbone.pkl' successfully, but failed to load tex_encode.pkl in the same way, the error is "./render/model/tex_encoder.pkl is a zip archive (did you mean to use torch.jit.load()?)", is the model upload error ?
@wuhaozhe

**Comment by wuhaozhe** [comment]
Hi, just use `torch.load("./render/model/tex_encoder.pkl")` works well in my environment, can you show me the error log? tex_encoder.pkl is a not zip archive, we just use torch.save() to save the model

**Comment by wuhaozhe** [comment]
you can check this issue https://github.com/pytorch/pytorch/issues/43766, and update the pytorch version to >= 1.6

**Comment by liyuanyaun** [comment]
i solve the problem when i update the pytorch version to >= 1.6, but i encounter another problem, the tex_encode.pkl input channel is 3, but its definition is 9, did you share the wrong model?

the error is "RuntimeError: Error(s) in loading state_dict for UNet:
        size mismatch for down1.conv.0.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 9, 3, 3])."

@wuhaozhe

**Comment by wuhaozhe** [comment]
I'm so sorry that we have uploaded the wrong model, we have updated the tex_encoder, you can download again from our link in readme.

**Comment by liyuanyaun** [comment]
> I'm so sorry that we have uploaded the wrong model, we have updated the tex_encoder, you can download again from our link in readme.

ok, thank you for your help

**Comment by liyuanyaun** [comment]
> I'm so sorry that we have uploaded the wrong model, we have updated the tex_encoder, you can download again from our link in readme.

i try to download again, but it seems not updated now

**Comment by wuhaozhe** [comment]
Hey, I have checked again, down1.conv.0.weight has size of torch.Size([64, 9, 3, 3]). Maybe your browser has cached the downloaded file? You can browse in private can download the model

**Comment by wuhaozhe** [comment]
> > I'm so sorry that we have uploaded the wrong model, we have updated the tex_encoder, you can download again from our link in readme.
> 
> i try to download again, but it seems not updated now

Hey, I have checked again, down1.conv.0.weight has size of torch.Size([64, 9, 3, 3]). Maybe your browser has cached the downloaded file? You can browse in private can download the model

**Comment by wuhaozhe** [comment]
> > I'm so sorry that we have uploaded the wrong model, we have updated the tex_encoder, you can download again from our link in readme.
> 
> i try to download again, but it seems not updated now

The download link of tex_encoder is same, but the model has been updated.

**Comment by liyuanyaun** [comment]
> > > I'm so sorry that we have uploaded the wrong model, we have updated the tex_encoder, you can download again from our link in readme.
> > 
> > 
> > i try to download again, but it seems not updated now
> 
> The download link of tex_encoder is same, but the model has been updated.

i changed browser， but it not work, size of my download is 51660kb

**Comment by wuhaozhe** [comment]
> > > > I'm so sorry that we have uploaded the wrong model, we have updated the tex_encoder, you can download again from our link in readme.
> > > 
> > > 
> > > i try to download again, but it seems not updated now
> > 
> > 
> > The download link of tex_encoder is same, but the model has been updated.
> 
> i changed browser， but it not work, size of my download is 51660kb

The model of mine is 52,899,530  bytes, what about yours?

**Comment by liyuanyaun** [comment]
> > > > > I'm so sorry that we have uploaded the wrong model, we have updated the tex_encoder, you can download again from our link in readme.
> > > > 
> > > > 
> > > > i try to download again, but it seems not updated now
> > > 
> > > 
> > > The download link of tex_encoder is same, but the model has been updated.
> > 
> > 
> > i changed browser， but it not work, size of my download is 51660kb
> 
> The model of mine is 52,899,530  bytes, what about yours?

same, sorry , i not update my model. thank you
