### ISSUE TITLE
bad result

### ISSUE THREAD

**Issue by liyuanyaun** [wuhaozhe/style_avatar#6]
use your model, demo code, example.png and example.wav, but the generated result is bad
![捕获](https://user-images.githubusercontent.com/22271564/141890614-10f64fbe-4db3-4f3f-879a-ee2653252505.PNG)

what is the problem？ @wuhaozhe

**Comment by wuhaozhe** [comment]
![image](https://user-images.githubusercontent.com/18577194/141919247-03fdf17c-2a4a-4d5d-b1a3-6f689592fe95.png)
hi, here is my generation results, let's check whether the model weight is correct?

could you please print the following results?
```
print(torch.load("./render/model/face_unet.pkl")['model.13.conv_block.1.weight'][0][0])
print(torch.load("./render/model/tex_encoder.pkl")['down1.conv.0.weight'][0][0])
```

My results are
```
tensor([[ 0.2953,  0.0757, -0.0737],
        [-0.1960, -0.0517,  0.0119],
        [ 0.0682,  0.2076,  0.0557]], device='cuda:0')

tensor([[ 0.1049, -0.1246,  0.0850],
        [-0.4058, -0.0189,  0.0529],
        [-0.1202, -0.0470, -0.0942]], device='cuda:0')
```

**Comment by liyuanyaun** [comment]
> ![image](https://user-images.githubusercontent.com/18577194/141919247-03fdf17c-2a4a-4d5d-b1a3-6f689592fe95.png) hi, here is my generation results, let's check whether the model weight is correct?
> 
> could you please print the following results?
> 
> ```
> print(torch.load("./render/model/face_unet.pkl")['model.13.conv_block.1.weight'][0][0])
> print(torch.load("./render/model/tex_encoder.pkl")['down1.conv.0.weight'][0][0])
> ```
> 
> My results are
> 
> ```
> tensor([[ 0.2953,  0.0757, -0.0737],
>         [-0.1960, -0.0517,  0.0119],
>         [ 0.0682,  0.2076,  0.0557]], device='cuda:0')
> 
> tensor([[ 0.1049, -0.1246,  0.0850],
>         [-0.4058, -0.0189,  0.0529],
>         [-0.1202, -0.0470, -0.0942]], device='cuda:0')
> ```

i try to print, but face_unet.pkl is different from you
![捕获](https://user-images.githubusercontent.com/22271564/141928341-b6c1c154-d280-4862-8f36-7b31cd5e6ed2.PNG)

**Comment by wuhaozhe** [comment]
> > ![image](https://user-images.githubusercontent.com/18577194/141919247-03fdf17c-2a4a-4d5d-b1a3-6f689592fe95.png) hi, here is my generation results, let's check whether the model weight is correct?
> > could you please print the following results?
> > ```
> > print(torch.load("./render/model/face_unet.pkl")['model.13.conv_block.1.weight'][0][0])
> > print(torch.load("./render/model/tex_encoder.pkl")['down1.conv.0.weight'][0][0])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My results are
> > ```
> > tensor([[ 0.2953,  0.0757, -0.0737],
> >         [-0.1960, -0.0517,  0.0119],
> >         [ 0.0682,  0.2076,  0.0557]], device='cuda:0')
> > 
> > tensor([[ 0.1049, -0.1246,  0.0850],
> >         [-0.4058, -0.0189,  0.0529],
> >         [-0.1202, -0.0470, -0.0942]], device='cuda:0')
> > ```
> 
> i try to print, but face_unet.pkl is different from you ![捕获](https://user-images.githubusercontent.com/22271564/141928341-b6c1c154-d280-4862-8f36-7b31cd5e6ed2.PNG)

My be something wrong with the face_unet.pkl, I have updated the download link, you can try again.

**Comment by liyuanyaun** [comment]
> > > ![image](https://user-images.githubusercontent.com/18577194/141919247-03fdf17c-2a4a-4d5d-b1a3-6f689592fe95.png) hi, here is my generation results, let's check whether the model weight is correct?
> > > could you please print the following results?
> > > ```
> > > print(torch.load("./render/model/face_unet.pkl")['model.13.conv_block.1.weight'][0][0])
> > > print(torch.load("./render/model/tex_encoder.pkl")['down1.conv.0.weight'][0][0])
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > My results are
> > > ```
> > > tensor([[ 0.2953,  0.0757, -0.0737],
> > >         [-0.1960, -0.0517,  0.0119],
> > >         [ 0.0682,  0.2076,  0.0557]], device='cuda:0')
> > > 
> > > tensor([[ 0.1049, -0.1246,  0.0850],
> > >         [-0.4058, -0.0189,  0.0529],
> > >         [-0.1202, -0.0470, -0.0942]], device='cuda:0')
> > > ```
> > 
> > 
> > i try to print, but face_unet.pkl is different from you ![捕获](https://user-images.githubusercontent.com/22271564/141928341-b6c1c154-d280-4862-8f36-7b31cd5e6ed2.PNG)
> 
> My be something wrong with the face_unet.pkl, I have updated the download link, you can try again.

this solved my case, thank you
