### ISSUE TITLE
Getting the UV mapping from UVAtlas

### ISSUE THREAD

**Issue by Armen-J** [wuhaozhe/style_avatar#9]
@wuhaozhe Thank you very much for sharing your code!
I have a question on how you generate the UV mappings
In the paper, you have mentioned that you use UVAtlas, but as I am going through your demo.py code, it seems that the UV maps are created by passing the 3DMM face model to the google Mesh_UV renderer.
Just to be exact: In [this method](https://github.com/wuhaozhe/style_avatar/blob/c314ecc6c9872346019bd0e567e9f84327c52c09/deep_3drecon/face_decoder.py#L347) of the Face3D, the [mesh_uv from mesh_renderer](https://github.com/wuhaozhe/style_avatar/blob/c314ecc6c9872346019bd0e567e9f84327c52c09/deep_3drecon/mesh_renderer/mesh_renderer.py#L406) is called.
Could you elaborate more on this, on how the UV maps of shape (H, W, 2) are generated.

**Comment by wuhaozhe** [comment]
Hi, this part of code is not uploaded. UV maps are generated offline, we use tools from https://github.com/microsoft/UVAtlas to generate uv maps.

**Comment by Armen-J** [comment]
Thanks for getting back. I have these question, I'd appreciate it if you could answer them:
1. By offline UV maps, do you mean the "uv.npy" file that is in the BFM folder?
2. Do you use UVAtlas to create the uv.npy? If yes, what data do you exactly give to UVAtlas.
3. For each rendering "uv.npy" is loaded and based on the 3D reconstructed geometry, using the mesh_renderer by Google the view is generated?

**Comment by wuhaozhe** [comment]
1. yes, uv.npy is the offline generated UV maps
2. UVAtlas creates uv.npy, the template bfm face model with zero expression and identity param is fed into the UVAtlas
3. yes, uv maps is consistent for each 3D reconstructed geometry

**Comment by Armen-J** [comment]
I am sorry to ask this question as my C++ knowledge is limited, but how do you exactly run UVAtlas? I installed Visual Studio Code, and basically opened the solution in it and built the UVAtlasTool which is giving me a "UVAtlasTool.exe", but how can I use all of this to create the "uv.npy" by giving a "average.obj" file.
I cannot find any resources on how to use UVAtlas, I hope you could provide some guidelines.

**Comment by wuhaozhe** [comment]
Hi, just run uvatlastool.exe, you donnot need to compile code yourself

**Comment by Armen-J** [comment]
I do it , but get this error:
"reading .\average_model.obj FAILED (80004005: Unspecified error)".
The screenshot is attached as well:
![image](https://user-images.githubusercontent.com/93533444/143523045-a9765425-f50d-43d9-8d7e-a8521c2d2bd5.png)

**Comment by wuhaozhe** [comment]
Oh, I haven't met this error, whether the downloaded uvatlastool.exe is corrupted? or you run x64 exe files on x86 machines?

**Comment by Armen-J** [comment]
Yes, it was an older uvatlastool.exe version that I was using. Just another question about working with UVAtlas, Can you please share what command you use to run it? I use this command: ".\uvatlastool.exe -wf .\average_mesh.obj".
This command returns a .obj file, but there's a problem! The number of vertices are increased (is more than 35709 of the file I pass in), and the new number is 36350.
Did you face this issue? How did you solve it?

**Comment by wuhaozhe** [comment]
Hi, I have run this tool one year ago, the command is already forgotten, sorry
